// Hot-spot coordinates are fractions of the image, so the image's true size is
// the one number that turns a pixel position into a correct answer key. These
// parsers exist instead of a 31MB dependency; the fixtures are generated by
// Pillow so they are real encoder output, not hand-built headers.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { readImageSize } from '../dist/imageMeta.js';

const dir = mkdtempSync(path.join(tmpdir(), 'imgmeta-'));
const script = `
from PIL import Image
import sys
d = sys.argv[1]
Image.new("RGB", (640, 360), (200, 30, 30)).save(d + "/a.png")
Image.new("RGB", (801, 451), (30, 200, 30)).save(d + "/a.jpg")
Image.new("RGB", (801, 451), (30, 200, 30)).save(d + "/prog.jpg", progressive=True)
Image.new("P", (120, 80)).save(d + "/a.gif")
`;

let havePillow = true;
try {
  execFileSync('python3', ['-c', script, dir], { stdio: 'pipe' });
} catch {
  havePillow = false;
}

test('PNG dimensions are read from the IHDR chunk', { skip: !havePillow }, () => {
  assert.deepEqual(readImageSize(readFileSync(path.join(dir, 'a.png'))),
    { width: 640, height: 360, format: 'png' });
});

// JPEG has no fixed offset for the size — it depends on which segments the
// encoder emitted and in what order, so this walks the segment chain.
test('JPEG dimensions are found by walking the segment chain', { skip: !havePillow }, () => {
  assert.deepEqual(readImageSize(readFileSync(path.join(dir, 'a.jpg'))),
    { width: 801, height: 451, format: 'jpeg' });
});

// A progressive JPEG uses SOF2 rather than SOF0, which an offset-guessing
// parser gets wrong while still returning plausible-looking numbers.
test('a progressive JPEG uses a different SOF marker and still reads', { skip: !havePillow }, () => {
  assert.deepEqual(readImageSize(readFileSync(path.join(dir, 'prog.jpg'))),
    { width: 801, height: 451, format: 'jpeg' });
});

test('GIF dimensions are little-endian, unlike PNG', { skip: !havePillow }, () => {
  assert.deepEqual(readImageSize(readFileSync(path.join(dir, 'a.gif'))),
    { width: 120, height: 80, format: 'gif' });
});

// Reporting a guess here would put a hotspot somewhere plausible and wrong,
// which is the whole failure mode this is meant to prevent.
test('an unrecognised file is undefined rather than a guess', () => {
  assert.equal(readImageSize(Buffer.from('hello world')), undefined);
  assert.equal(readImageSize(Buffer.alloc(0)), undefined);
  assert.equal(readImageSize(Buffer.from('%PDF-1.7\n%\xe2\xe3\xcf\xd3')), undefined);
});

// A truncated download must not be read as a valid header.
test('a truncated PNG is not reported as readable', () => {
  const png = readFileSync(path.join(dir, 'a.png'));
  assert.equal(readImageSize(png.subarray(0, 16)), undefined);
});
